services:
  - type: web
    name: ims-php-app
    env: docker
    plan: starter
    dockerfilePath: Dockerfile.prod
    envVars:
      - key: DB_HOST
        value: $DB_HOST
        scope: RUN_AND_BUILD
      - key: DB_USER
        value: $DB_USER
        scope: RUN_AND_BUILD
      - key: DB_PASS
        value: $DB_PASS
        scope: RUN_AND_BUILD
      - key: DB_NAME
        value: $DB_NAME
        scope: RUN_AND_BUILD
